PREPACKAGED_EXAMPLES = {
    "A chill lo-fi hip hop beat at 80 BPM. Soft, jazzy electric piano seventh chords playing a relaxed progression, layered over a slow, simple drum beat.": {
        "brief": "### Style/Genre\nDreamy Lo-Fi Hip Hop\n\n### Section Plan\n- **Intro**: 4 bars. Rhodes piano only.\n- **Verse**: 8 bars. Rhodes + drums.\n- **Chorus**: 8 bars. Rhodes + drums + warm synth lead.\n- **Outro**: 4 bars. Fading rhodes chords.\n*Total 24 bars (~1:12 minutes)*",
        "code": "from musicpy import *\n\nfull_rhodes = ((C('Dm9', 4) % (1, 0)) | (C('G13', 4) % (1, 0)) | (C('Cmaj9', 4) % (1, 0)) | (C('Am7', 4) % (1, 0))) * 6 # 24 bars total\nfull_drums = (drum('K, H, S, H, K, -, S, H') * 16).notes # 16 bars total\nchorus_melody = (chord('D5, E5, F5, G5') % (1/2, 1/2)) * 4 # 8 bars total\n\nt1 = track(full_rhodes, instrument=5, start_time=0)\nt2 = track(full_drums, channel=9, start_time=4)\nt3 = track(chorus_melody, instrument=81, start_time=12)\nresult = build(t1, t2, t3, bpm=80)"
    },
    "An upbeat, driving 80s synthwave track at 130 BPM. It features a fast, pulsing 16th-note synth bassline, a catchy bright synthesizer melody, and a driving four-on-the-floor drum beat.": {
        "brief": "### Style/Genre\nUpbeat Synthwave / Synth-Pop\n\n### Section Plan\n- **Intro**: 8 bars. Driving bassline only.\n- **Build**: 8 bars. Bass + 4-on-the-floor drums.\n- **Drop / Chorus**: 16 bars. Add catchy sawtooth lead melody.\n- **Outro**: 8 bars. Bass fading out alone.\n*Total 40 bars (~1:13 minutes)*",
        "code": "from musicpy import *\n\nbass_pattern = chord('C2, C2, C2, C2, G1, G1, G1, G1') % (1/16, 1/16) # 1/2 bar\nfull_bass = bass_pattern * 80 # 40 bars total\ndance_drums = (drum('K, H, S, H, K, H, S, H') * 24).notes # 24 bars total\nmelody_loop = (chord('C5, G5, -, F5, D#5, -, D5, C5') % (1/8, 1/8)) * 16 # 16 bars total\n\nt1 = track(full_bass, instrument=40, start_time=0)\nt2 = track(dance_drums, channel=9, start_time=8)\nt3 = track(melody_loop, instrument=82, start_time=16)\nresult = build(t1, t2, t3, bpm=130)"
    },
    "A slow, grandiose cinematic string progression at 60 BPM. Long, sustained minor and major chords swelling out slowly to create a sense of scale and heroism.": {
        "brief": "### Style/Genre\nCinematic Orchestral Build\n\n### Section Plan\n- **Intro**: 8 bars. Deep cello and bass strings establishing chords.\n- **Main Swell**: 16 bars. Introduce high octave violin strings for heroism.\n- **Outro**: 8 bars. Soft resolution back to only lower strings.\n*Total 32 bars (~2:08 minutes)*",
        "code": "from musicpy import *\n\nintro_strings = (C('Cm', 4) % (2, 0)) | (C('Ab', 4) % (2, 0)) | (C('Eb', 4) % (2, 0)) | (C('Bb', 3) % (2, 0)) # 8 bars\nfull_strings = intro_strings * 4 # 32 bars total\n\nhigh_strings = (C('Cm', 5) % (2, 0)) | (C('Ab', 5) % (2, 0)) | (C('Eb', 5) % (2, 0)) | (C('Bb', 4) % (2, 0))\nmain_high_strings = high_strings * 2 # 16 bars total\n\nt1 = track(full_strings, instrument=49, start_time=0)\nt2 = track(main_high_strings, instrument=48, start_time=8)\nresult = build(t1, t2, bpm=60)"
    },
    "A fast and aggressive pop punk rock loop at 160 BPM. Distorted electric guitar power chords playing eighth notes, over loud rock drum patterns.": {
        "brief": "### Style/Genre\nEnergetic Pop Punk\n\n### Section Plan\n- **Intro**: 4 bars. Solo aggressive rock drum beat.\n- **Verse**: 16 bars. Distorted guitar rhythm chug + drums.\n- **Chorus**: 16 bars. Add high octave lead guitar for width.\n- **Outro**: 8 bars. Just drums finishing the track.\n*Total 44 bars (~1:06 minutes)*",
        "code": "from musicpy import *\n\npower_chords = (C('C5', 3) % (1/8, 1/8) * 4) | (C('G5', 3) % (1/8, 1/8) * 4) | (C('A5', 3) % (1/8, 1/8) * 4) | (C('F5', 3) % (1/8, 1/8) * 4) # 4 bars\nfull_guitars = power_chords * 8 # 32 bars\nfull_drums = (drum('K, -, S, -, K, K, S, -') * 44).notes # 44 bars\nlead_guitar = (chord('C5, D5, E5, C5') % (1/2, 1/2)) * 8 # 16 bars\n\nt1 = track(full_drums, channel=9, start_time=0)\nt2 = track(full_guitars, instrument=30, start_time=4)\nt3 = track(lead_guitar, instrument=29, start_time=20)\nresult = build(t1, t2, t3, bpm=160)"
    },
    "A delicate classical piece for solo acoustic grand piano at 100 BPM. It features fast, flowing A minor arpeggios that rise and fall gracefully.": {
        "brief": "### Style/Genre\nClassical Solo Piano\n\n### Section Plan\n- **Part A**: 8 bars. Soft cascading A minor / D minor arpeggios.\n- **Part B**: 8 bars. Tension shift using E minor climbs.\n- **Part A Return**: 8 bars. Resolve back to familiar motif.\n- **Outro**: 4 bars. Simple 4-bar sustain on A minor root.\n*Total 28 bars (~1:07 minutes)*",
        "code": "from musicpy import *\n\narp_am = chord('A3, C4, E4, A4, C5, A4, E4, C4') % (1/16, 1/16) * 2 # 1 bar\narp_dm = chord('D4, F4, A4, D5, F5, D5, A4, F4') % (1/16, 1/16) * 2 # 1 bar\narp_em = chord('E4, G4, B4, E5, G5, E5, B4, G4') % (1/16, 1/16) * 2 # 1 bar\n\nprog_A = (arp_am * 2) | (arp_dm * 2) # 4 bars\nprog_B = (arp_em * 2) | (arp_am * 2) # 4 bars\n\nfull_piece = prog_A * 2 | prog_B * 2 | prog_A * 2 # 24 bars\nend_chord = C('Am', 3) % (4, 0) # 4 bars (ringing out)\n\nt1 = track(full_piece | end_chord, instrument=1, start_time=0)\nresult = build(t1, bpm=100)"
    },
    "A heavy, booming dubstep track at 140 BPM. It features a slow, half-time beat with a massive snare drum, and aggressive, modulating electronic synthesizer growls.": {
        "brief": "### Style/Genre\nAggressive Dubstep\n\n### Section Plan\n- **Intro**: 8 bars. Eerie atmospheric synth pads and sub bass.\n- **Build**: 8 bars. Fast snare rolls and risers.\n- **Drop**: 16 bars. Heavy half-time beat and aggressive bass growls.\n- **Outro**: 8 bars. Bass fading out alone into atmosphere.\n*Total 40 bars (~1:08 minutes)*",
        "code": "from musicpy import *\n\nsub_bass = chord('F1') % (1, 1) * 40 # 40 bars total\npads = C('Fm9', 4) % (4, 0) * 10 # 40 bars total\nhalf_time_drums = (drum('K, -, -, -, S, -, -, -') * 16).notes # 16 bars total\ngrowl_bass = chord('F1, Ab1, F1, Eb1, F2, Eb2, F1, Ab1') % (1/8, 1/8) * 16 # 16 bars total\n\nt1 = track(sub_bass, instrument=88, start_time=0)\nt2 = track(pads, instrument=91, start_time=0)\nt3 = track(half_time_drums, channel=9, start_time=16)\nt4 = track(growl_bass, instrument=88, start_time=16)\nresult = build(t1, t2, t3, t4, bpm=140)"
    },
    "A 12-bar blues classic in E major at 110 BPM. Shuffle feel with an electric guitar playing the rhythmic shuffle riff, a piano adding turnarounds, and straight blues drums.": {
        "brief": "### Style/Genre\nShuffle Blues\n\n### Section Plan\n- **Intro**: 4 bars. Piano turnaround + drums.\n- **Verse 1**: 12 bars. Guitar riff + bass + drums.\n- **Solo**: 12 bars. Piano solos over the form.\n- **Outro**: 4 bars. Fast turnaround ending on root.\n*Total 32 bars (~1:10 minutes)*",
        "code": "from musicpy import *\n\nrhythm_intervals = [1/6, 1/12, 1/6, 1/12, 1/6, 1/12, 1/6, 1/12]\nriff_E_bar = chord('E2, B2, E2, C#3, E2, B2, E2, C#3') % (rhythm_intervals, rhythm_intervals)\nriff_A_bar = chord('A1, E2, A1, F#2, A1, E2, A1, F#2') % (rhythm_intervals, rhythm_intervals)\nriff_B_bar = chord('B1, F#2, B1, G#2, B1, F#2, B1, G#2') % (rhythm_intervals, rhythm_intervals)\nblues_12_bar = (riff_E_bar * 4) | (riff_A_bar * 2) | (riff_E_bar * 2) | riff_B_bar | riff_A_bar | (riff_E_bar * 2)\n\nintro_piano = C('E7', 4) % (4, 0)\nintro_drums = (drum('K, H, S, H, K, H, S, H') * 4).notes # 4 bars\nverse_guitar = blues_12_bar * 2 # 24 bars\nverse_drums = (drum('K, H, S, H, K, H, S, H') * 24).notes # 24 bars\nverse_bass = chord('E2, G2, G#2, B2, E2, G2, G#2, B2') % (rhythm_intervals, rhythm_intervals) * 24 # 24 bars\nsolo_piano = chord('E5, E5, D5, D5, B4, B4, A4, A4') % (rhythm_intervals, rhythm_intervals) * 12 # 12 bars\noutro_hit = C('E7', 3) % (4, 0)\n\nt1 = track(intro_piano, instrument=1, start_time=0)\nt2 = track(intro_drums, channel=9, start_time=0)\nt3 = track(verse_guitar, instrument=30, start_time=4)\nt4 = track(verse_bass, instrument=33, start_time=4)\nt5 = track(verse_drums, channel=9, start_time=4)\nt6 = track(solo_piano, instrument=1, start_time=16)\nt7 = track(outro_hit, instrument=1, start_time=28)\nresult = build(t1, t2, t3, t4, t5, t6, t7, bpm=110)"
    },
}